language: node_js

sudo: false

node_js: '10'

branches:
  only:
    - master

cache: yarn

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

#before_install:
#  - nvm install 0.12

install:
  - yarn install

before_script:
  - yarn run gulp prod

script:
  - yarn run test

#after_script:
#  - php ./vendor/bin/coveralls
