language: node_js

sudo: false

node_js: '6'

branches:
  only:
    - master

cache: yarn

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_install:
  - yarn install --production
#  - nvm install 0.12
#  - nvm use 0.12
#  - cd $TRAVIS_BUILD_DIR/javascript && npm config set spin false

install:
  - composer install --no-progress --no-interaction --prefer-dist
#  - cd $TRAVIS_BUILD_DIR/javascript && npm install --no-progress

before_script:
  - mkdir -p build/logs
  - echo 'date.timezone = "America/Los_Angeles"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - composer run test
#  - cd $TRAVIS_BUILD_DIR/javascript && npm run test

after_script:
  - php ./vendor/bin/coveralls
