language: node_js

sudo: false

node_js: '10'

branches:
  only:
    # - master
    - typescript

cache: yarn

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

install:
  - yarn install

before_script:
  - yarn build

script:
  - yarn run gh-pages -d public/
